
FAIL DedicatedWorker should correctly handle abrupt completion promise_test: Unhandled rejection with value: object "ReferenceError: Can't find variable: SharedWorker"
FAIL SharedWorker should correctly handle abrupt completion promise_test: Unhandled rejection with value: object "ReferenceError: Can't find variable: SharedWorker"

